### ISSUE TITLE
Bug: StarSearch for Workspaces prevents page scrolling

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3618]
When using StarSearch for workspaces on a larger screen, StarSearch works as expected, but you are unable to scroll the page if the content overflows the viewport.

This is because when StarSearch the page was built, we wanted to prevent page scrolling and have the chat area be the only scrollable region on the page.

```css
body:has(.star-search) {
  overflow: hidden;
}
```

See https://github.com/open-sauced/app/blob/beta/styles/globals.css#L290-L292

The fix is to add a [:not()](https://developer.mozilla.org/en-US/docs/Web/CSS/:not) with some sort of criteria to indicate that StarSearch is embedded, e.g.

```css
body:has(.star-search:not([data-is-embedded="true"])) {
  overflow: hidden;
}
```

so that it prevents scrolling of the `<body />` on the StarSearch page but not when it's embedded.

[Related Slack Conversation](https://opensaucedworkspace.slack.com/archives/C052YRD69JN/p1718984462444839)
